development:
  adapter: postgresql
  encoding: unicode
  database: tredule_redo_development

test:
  adapter: postgresql
  encoding: unicode
  database: tredule_redo_test

production:
  adapter: postgresql
  encoding: unicode
  database: tredule_redo_production